// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_l8-kDL73T-BAjBOtYoxcLSwoqVmm6xk',
    appId: '1:376717499507:web:7af34e88afb4f869d19e06',
    messagingSenderId: '376717499507',
    projectId: 'sawari-e4ebf',
    authDomain: 'sawari-e4ebf.firebaseapp.com',
    storageBucket: 'sawari-e4ebf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwNSBEJVTt_kZg15zd280voUtGfLRQAA',
    appId: '1:376717499507:android:54a613661494f3fed19e06',
    messagingSenderId: '376717499507',
    projectId: 'sawari-e4ebf',
    storageBucket: 'sawari-e4ebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQGCVVtziRIEHbz2n_lfNjshTWPj-uds',
    appId: '1:376717499507:ios:3090e803fbb3fde2d19e06',
    messagingSenderId: '376717499507',
    projectId: 'sawari-e4ebf',
    storageBucket: 'sawari-e4ebf.firebasestorage.app',
    iosBundleId: 'com.example.sawari',
  );
}
