import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'auth_gate.dart';
import 'firebase_options.dart';
import 'get_started.dart';
import 'splash.dart';

Future<void> main() async {
  // Ensure Flutter bindings are initialized before accessing SystemChrome
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase. firebase_options.dart is generated by
  // `flutterfire configure`. If you have not run that yet, this will throw
  // at runtime — see README/setup instructions.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Set global transparent status bar for a modern edge-to-edge look
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
    ),
  );

  // Lock orientation to portrait (Standard practice for ride-hailing apps)
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  runApp(const MyApp());
}

// Global notifier for theme switching
final ValueNotifier<ThemeMode> themeNotifier = ValueNotifier(ThemeMode.light);

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeMode>(
      valueListenable: themeNotifier,
      builder: (_, ThemeMode currentMode, __) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'Sawari',
          themeMode: currentMode,
          theme: _buildLightTheme(),
          darkTheme: _buildDarkTheme(),
          home: const SplashScreen(),
          routes: {
            // After splash, AuthGate decides where to send the user based on
            // Firebase auth state and Firestore profile role.
            '/home': (context) => const AuthGate(),
            '/get-started': (context) => const GetStartedScreen(),
          },
        );
      },
    );
  }

  ThemeData _buildLightTheme() {
    return ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: const Color(0xFF0F265C), // Brand Deep Blue
        primary: const Color(0xFF2B5DA6),
        secondary: const Color(0xFFD4AF37), // Brand Gold
        brightness: Brightness.light,
      ),
      // Soft slate background matching your newly polished tabs
      scaffoldBackgroundColor: const Color(0xFFF1F5F9),
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.transparent,
        foregroundColor: Color(0xFF0F172A),
        elevation: 0,
        centerTitle: true,
      ),
      // Standardize button shapes across the app
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
        ),
      ),
    );
  }

  ThemeData _buildDarkTheme() {
    return ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: const Color(0xFF2B5DA6),
        primary: const Color(0xFF3B82F6), // Lighter blue for dark mode visibility
        secondary: const Color(0xFFD4AF37),
        brightness: Brightness.dark,
        surface: const Color(0xFF1E293B),
      ),
      // Deep slate background matching your newly polished tabs
      scaffoldBackgroundColor: const Color(0xFF0F172A),
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.transparent,
        foregroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
      ),
      // Standardize button shapes across the app
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
        ),
      ),
    );
  }
}